---
- import_tasks: installation.yaml

- import_tasks: configuration.yaml

- import_tasks: systemd.yaml
  when:
    - ansible_virtualization_type is defined
    - ansible_virtualization_type != "docker"
