---

- name: "Add healthchecker user"
  become_user: root
  become: true
  user:
      name: "{{ healthcheck__user }}"

- name: Ensure we have python/pip and setup tools installed
  become_user: root
  become: true
  package:
      name:
          - python3
          - python3-pip
          - python3-setuptools
          - python-pip
          - python-setuptools

- name: Install virtualenv
  become_user: root
  become: true
  pip:
      name:
          - virtualenv

- name: Install requirements using pip
  become_user: root
  become: true
  pip:
      name:
          - "{{ healthcheck__install_package }}"
          - pyyaml
      state: present
      virtualenv: "{{ healthcheck__install_env }}"
      virtualenv_python: python3

- name: Copy UWSGI config
  become: true
  template:
      src: "uwsgi.ini.j2"
      dest: "{{ healthcheck__path_to_wsgi }}"
      owner: root
      group: root
  notify: Restart healthchecker

- name: Create install directiory
  become: true
  file:
      path: "{{ healthcheck__install_path }}"
      state: directory
      owner: "{{ healthcheck__user }}"

- name: Create configuration file
  become: true
  template:
      src: config.ini.j2
      dest: "{{ healthcheck__install_path }}/config.yaml"
  notify: Restart healthchecker

- name: Setup systemd file for {{ healthcheck__instance }}
  become: true
  template:
      src: "systemd-service.service.j2"
      dest: "/etc/systemd/system/{{ healthcheck__service }}"
  notify: Restart healthchecker

- name: Ensure Healthchecker is running through Systemd
  become: true
  systemd:
      name: "graphene-healthchecks-{{ healthcheck__instance }}.service"
      daemon_reload: true
      enabled: true
      state: started

- name: See if the healthchecker is running
  wait_for:
      host: "localhost"
      port: "{{ healthcheck__listen_port }}"
      timeout: 10
