---
- name: Restart healthchecker
  become: true
  service:
      name: graphene-healthchecks-{{healthcheck__instance}}.service
      state: restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
