---

- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Install python2
      become: true
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get install -y python)
      tags:
        # Skip ANSIBLE0012 Commands should not change things if nothing needs doing
        # Determine if nginx is enabled
        - skip_ansible_lint
    - name: "setup"
      setup:
  roles:
    - role: graphene-healthchecker
      # Variables
      healthcheck__user: healthcheck
      healthcheck__instance: healthcheck
      healthcheck__service: graphene-healthchecks-{{healthcheck__instance}}.service
      healthcheck__install_path: /home/{{healthcheck__user}}/healthcheck_{{healthcheck__instance}}/
      healthcheck__install_env: /home/{{healthcheck__user}}/healthcheck_{{healthcheck__instance}}/env
      healthcheck__path_to_wsgi: /home/{{healthcheck__user}}/healthcheck_{{healthcheck__instance}}/uwsg.ini
      healthcheck__listen_host: 0.0.0.0
      healthcheck__listen_port: 8080
      healthcheck__witness_url: https://node.bitshares.eu
